### PR TITLE
Custom shared preload libraries

### LINKED ISSUE #2526: Unable to set shared_preload_libraries when exporter turned on
## Overview

When monitoring/the metric exporter is turned on, then `shared_preload_libraries` gets hard coded to `pg_stat_statements,pgnodemx`

```
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
```

## Environment

Please provide the following details:

- Platform: EKS
- Platform Version: 5.0.0
- PGO Image Tag: ubi8-5.0.0-0
- Postgres Version 13

## Steps to Reproduce

Create a PostgresCluster with e.g.:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: horse
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-4.7.0
  postgresVersion: 13
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
  instances:
    - name: demo
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
```

Observe that timescaledb is preloaded:
```
$ PG_CLUSTER_PRIMARY_POD=$(kubectl -o name -l postgres-operator.crunchydata.com/cluster=horse,postgres-operator.crunchydata.com/role=master)
$ kubectl exec -it ${PG_CLUSTER_PRIMARY_POD} -c database  -- patronictl show-config | grep shared_preload_libraries
    shared_preload_libraries: timescaledb
```

Now, try with this instead (adds `monitoring` section):
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: horse
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-4.7.0
  postgresVersion: 13
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
  instances:
    - name: demo
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
```

Observe that timescaledb is not loaded:
```
$ PG_CLUSTER_PRIMARY_POD=$(kubectl -o name -l postgres-operator.crunchydata.com/cluster=horse,postgres-operator.crunchydata.com/role=master)
$ kubectl exec -it ${PG_CLUSTER_PRIMARY_POD} -c database  -- patronictl show-config | grep shared_preload_libraries
    shared_preload_libraries: pg_stat_statements,pgnodemx
```

## Additional Information

Where the new value is coming from: https://github.com/CrunchyData/postgres-operator/blob/21905f0c2962e22f72aec34a9cad733e31afcdf0/internal/pgmonitor/postgres.go#L57-L69
However the old value was not available in that code; my user-provided `dynamicConfiguration` is merged here: https://github.com/CrunchyData/postgres-operator/blob/21905f0c2962e22f72aec34a9cad733e31afcdf0/internal/patroni/config.go#L224

### PR DESCRIPTION
**Pull request by tjmoore4**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [x] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
Currently, when monitoring is turned on, the shared_preload_libraries
get hard coded to 'pg_stat_statements,pgnodemx' because of how the
mandatory parameters are being set by the Operator.

**What is the new behavior (if this is a feature change)?**
This updates the behavior so that user defined shared_preload_libraries
are appended to the existing list, leaving the mandatory libraries in place
while keeping any user defined libraries as well.

Additionally, (separate commit) the "k8s.io/api/core/v1" package was imported as both
"corev1" and "v1" in certain files. This standardizes on the earlier usage of "v1".

**Other information**:
[ch11921]
fixes #2526

### CODE REVIEW

File: internal/controller/postgrescluster/controller.go [hunk 1]
```diff
@@ -156,7 +155,7 @@ func (r *Reconciler) Reconcile(
 		primaryCertificate       *v1.SecretProjection
 		pgUser                   *v1.Secret
 		rootCA                   *pki.RootCertificateAuthority
-		monitoringSecret         *corev1.Secret
+		monitoringSecret         *v1.Secret
```
Comment (cbandy) [inline internal/controller/postgrescluster/controller.go:158]: 📝 This change is fine. New code should use `corev1`.

File: internal/patroni/config.go [hunk 2]
```diff
@@ -260,7 +260,17 @@ func DynamicConfiguration(
...
 		for k, v := range pgParameters.Mandatory.AsMap() {
-			parameters[k] = v
+			// Unlike other PostgreSQL parameters that have mandatory values,
+			// shared_preload_libraries is a comma separated list that can have
+			// other values appended in addition to the mandatory values. Below,
+			// any values provided in the CRD are appended after the mandatory
+			// values.
+			_, ok := parameters[k]
+			if k == "shared_preload_libraries" && ok {
+				parameters[k] = v + "," + parameters[k].(string)
```
[the remark this answers is not in the document]
Comment (tjmoore4) [reply internal/patroni/config.go:270]: Yes, it can cause a panic, thanks for the catch. I've updated the code to match your suggestion and added a test for this case. Thanks!

File: internal/controller/postgrescluster/controller.go (hunk 1 above)
Comment (tjmoore4) [reply internal/controller/postgrescluster/controller.go:158]: Updated to use `corev1`.

**Review by cbandy — APPROVED** [review]
